In [1]:
import pandas as pd
import numpy as np
import math


import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data_path = 'data/originals/'
country_path = 'data/countries/'
graph_path = 'data/graph/'
with_country_path = 'data/with_country/'
# climate_models = ['gs', 'he', 'mr', 'cc']
climate_model = 'he'

In [3]:
cal_per_year_person = 2.355e6 * 365

In [5]:
data_2000 = pd.read_csv(with_country_path + '2000_country.csv', index_col='pixel_id')
data_ssp1 = pd.read_csv(with_country_path + 'SSP1_country.csv', index_col='pixel_id')
data_ssp2 = pd.read_csv(with_country_path + 'SSP2_country.csv', index_col='pixel_id')
data_ssp3 = pd.read_csv(with_country_path + 'SSP3_country.csv', index_col='pixel_id')
data_ssp4 = pd.read_csv(with_country_path + 'SSP4_country.csv', index_col='pixel_id')
data_ssp5 = pd.read_csv(with_country_path + 'SSP5_country.csv', index_col='pixel_id')

scenarios = [data_ssp1, data_ssp2, data_ssp3, data_ssp4, data_ssp5]
scenario_names = ['SSP1', 'SSP2', 'SSP3', 'SSP4', 'SSP5']

FileNotFoundError: File b'data/with_country/2000_country.csv' does not exist

In [5]:
data_2000.head()

,Unnamed: 0,Calories 2000,%cropland 2000,log(cal_per_ha) 2000,cal_per_ha 2000,lat,lon,ha_per_pixel,Temperature 2000,Precipitation 2000,workability_index 2000,slope,altitude,Population 2000,country,continent
pixel_id,,,,,,,,,,,,,,,,
776595,0,0.0,0.005203,0.0,0.0,-75.00,96.25,2215.1946,-14.860833,252.0,6,89.85227,106,1.032100,Russia,Asia
780822,1,0.0,0.001041,0.0,0.0,-74.92,88.50,2227.2866,-13.847250,253.0,6,89.91569,77,1.062673,Russia,Asia
780823,2,0.0,0.011446,0.0,0.0,-74.92,88.58,2227.2866,-13.884583,254.0,6,89.90728,90,1.063494,Russia,Asia
780827,3,0.0,0.003122,0.0,0.0,-74.92,88.92,2227.2866,-13.993375,250.0,6,89.12331,91,1.048804,Russia,Asia
780915,4,0.0,0.007284,0.0,0.0,-74.92,96.25,2227.2866,-14.763250,252.0,6,89.63344,88,1.040066,Russia,Asia

In [6]:
data_ssp1.head()

,Unnamed: 0,Calories 2050,ΔCalories,%cropland 2050,log(cal_per_ha) 2050,cal_per_ha 2050,Δlog(cal_per_ha),Δcal_per_ha,lat,lon,ha_per_pixel,Temperature 2050,Precipitation 2050,workability_index 2050,slope,altitude,Population 2050,country,continent
pixel_id,,,,,,,,,,,,,,,,,,,
776595,0,5.516018e+10,5.516018e+10,0.005203,22.288948,4.785939e+09,22.288948,4.785939e+09,-75.00,96.25,2215.1946,-85,324,6,89.85227,106,0.0,Russia,Asia
780822,1,1.176765e+10,1.176765e+10,0.001041,22.348055,5.077348e+09,22.348055,5.077348e+09,-74.92,88.50,2227.2866,-74,313,6,89.91569,77,0.0,Russia,Asia
780823,2,1.276891e+11,1.276891e+11,0.011446,22.334404,5.008508e+09,22.334404,5.008508e+09,-74.92,88.58,2227.2866,-74,314,6,89.90728,90,0.0,Russia,Asia
780827,3,3.435064e+10,3.435064e+10,0.003122,22.320710,4.940386e+09,22.320709,4.940386e+09,-74.92,88.92,2227.2866,-75,313,6,89.12331,91,0.0,Russia,Asia
780915,4,7.741126e+10,7.741126e+10,0.007284,22.285923,4.771483e+09,22.285923,4.771483e+09,-74.92,96.25,2227.2866,-83,323,6,89.63344,88,0.0,Russia,Asia

In [7]:
# Country 2000
total_cal_2000 = data_2000['Calories 2000'].sum()
cal_country_2000 = data_2000.groupby('country')['Calories 2000'].sum()
cal_perc_country_2000 = 100 * cal_country_2000 / total_cal_2000
population_country_2000 = data_2000.groupby('country')['Population 2000'].sum()
cropland_per_country_2000 = 100 * data_2000.groupby('country')['%cropland 2000'].mean()
cal_requirements_country_2000 = population_country_2000 * cal_per_year_person
sufficiency_country_2000 = 100 * cal_country_2000 / cal_requirements_country_2000
cropland_yield_country_2000 = data_2000.groupby('country')['cal_per_ha 2000'].mean()
country_2000 = pd.concat([cal_country_2000, population_country_2000, cal_requirements_country_2000, cropland_per_country_2000, sufficiency_country_2000, cal_perc_country_2000, cropland_yield_country_2000], axis=1) 
country_2000.columns = ['Calories2000', 'Population2000', 'Calory_requirements_2000', 'Cropland2000', 'Sufficiency2000', 'Percentage_of_total_cal2000', 'Yield2000']
country_2000.head()

,Calories 2000,Population 2000,Calory requirements 2000,Cropland (%) 2000,Sufficiency (%) 2000,Percentage of total cal 2000,Yield 2000
country,,,,,,,
Afghanistan,2.283608e+16,1.944503e+07,1.671446e+16,15.554691,136.624695,0.135345,2.473385e+09
Albania,1.006859e+16,2.927077e+06,2.516042e+15,50.130491,400.175647,0.059674,6.714505e+09
Algeria,2.037171e+16,2.564769e+07,2.204612e+16,16.241037,92.404971,0.120739,5.088947e+08
Angola,1.306303e+16,1.417293e+07,1.218270e+16,6.381354,107.226094,0.077422,1.874494e+09
Argentina,4.744144e+17,3.203618e+07,2.753750e+16,33.925728,1722.794086,2.811758,6.539490e+09

In [8]:
# Continent 2000
cal_continent_2000 = data_2000.groupby('continent')['Calories 2000'].sum()
cal_perc_continent_2000 = 100 * cal_continent_2000 / total_cal_2000
population_continent_2000 = data_2000.groupby('continent')['Population 2000'].sum()
cropland_per_continent_2000 = 100 * data_2000.groupby('continent')['%cropland 2000'].mean()
cal_requirements_continent_2000 = population_continent_2000 * cal_per_year_person
sufficiency_continent_2000 = 100 * cal_continent_2000 / cal_requirements_continent_2000
cropland_yield_continent_2000 = data_2000.groupby('continent')['cal_per_ha 2000'].mean()
continent_2000 = pd.concat([cal_continent_2000, population_continent_2000, cal_requirements_continent_2000, cropland_per_continent_2000, sufficiency_continent_2000, cal_perc_continent_2000, cropland_yield_continent_2000], axis=1) 
continent_2000.columns = ['Calories2000', 'Population2000', 'Calory_requirements_2000', 'Cropland2000', 'Sufficiency2000', 'Percentage_of_total_cal2000', 'Yield2000']
continent_2000

,Calories 2000,Population 2000,Calory requirements 2000,Cropland (%) 2000,Sufficiency (%) 2000,Percentage of total cal 2000,Yield 2000
continent,,,,,,,
Africa,1.363561e+18,7.334935e+08,6.304927e+17,24.887335,216.269136,8.081548,2.384413e+09
Asia,7.488754e+18,3.517988e+09,3.023975e+18,34.448474,247.646077,44.384318,4.937351e+09
Europe,2.539432e+18,5.120630e+08,4.401566e+17,46.712172,576.938269,15.050694,9.083798e+09
North America,3.229554e+18,4.154076e+08,3.570740e+17,26.283100,904.449405,19.140906,9.475244e+09
Oceania,3.342907e+17,1.971964e+07,1.695051e+16,26.215583,1972.157156,1.981273,3.930828e+09
South America,1.840040e+18,3.090533e+08,2.656545e+17,24.774663,692.643980,10.905540,4.825606e+09
Unknown,7.689176e+16,5.334733e+07,4.585603e+16,25.799204,167.680795,0.455722,5.333275e+09

In [9]:
demand_2000 = country_2000['Calory requirements 2000'].sum()
production_2000 = country_2000['Calories 2000'].sum()
print('World demand 2000: {:,}\nWorld production 2000: {:,}'.format(demand_2000, production_2000))

World demand 2000: 4.780158814929363e+18
World production 2000: 1.6872523092193595e+19

In [10]:
for scenario, name in zip(scenarios, scenario_names):
    # Country 2050
    total_cal = scenario['Calories 2050'].sum()
    cal_country = scenario.groupby('country')['Calories 2050'].sum()
    cal_perc_country = 100 * cal_country / total_cal
    population_country = scenario.groupby('country')['Population 2050'].sum()
    cropland_per_country = 100 * scenario.groupby('country')['%cropland 2050'].mean()
    cal_requirements_country = population_country * cal_per_year_person
    sufficiency_country = 100 * cal_country / cal_requirements_country
    cropland_yield_country = scenario.groupby('country')['cal_per_ha 2050'].mean()
    country = pd.concat([cal_country, population_country, cal_requirements_country, cropland_per_country, sufficiency_country, cal_perc_country, cropland_yield_country], axis=1) 
    country.columns = ['Calories 2050', 'Population 2050', 'Calory requirements 2050', 'Cropland (%) 2050', 'Sufficiency (%) 2050', 'Percentage of total cal 2050', 'Yield 2050']
    
    # Delta country 2000 - 2050
    delta_cal_country = 100*scenario.groupby('country')['ΔCalories'].sum() / country_2000['Calories 2000']
    delta_pop_country = 100*(country['Population 2050'] - country_2000['Population 2000'])/country_2000['Population 2000']
    delta_yield_country = 100*(country['Yield 2050'] - country_2000['Yield 2000']) / country_2000['Yield 2000']
    delta_cal_req_country = 100*(country['Calory requirements 2050'] - country_2000['Calory requirements 2000']) / country_2000['Calory requirements 2000']
    delta_country = pd.concat([delta_cal_country, delta_pop_country, delta_cal_req_country, delta_yield_country], axis=1)
    delta_country.columns = ['ΔCalories (%)', 'ΔPopulation (%)', 'ΔCalory requirements (%)', 'ΔYield (%)']
    country = country_2000.join(country, on='country').join(delta_country, on='country')
    
    
    # Continent 2050
    cal_continent = scenario.groupby('continent')['Calories 2050'].sum()
    cal_perc_continent = 100 * cal_continent / total_cal
    population_continent = scenario.groupby('continent')['Population 2050'].sum()
    cropland_per_continent = 100 * scenario.groupby('continent')['%cropland 2050'].mean()
    cal_requirements_continent = population_continent * cal_per_year_person
    sufficiency_continent = 100 * cal_continent / cal_requirements_continent
    cropland_yield_continent = scenario.groupby('continent')['cal_per_ha 2050'].mean()
    continent = pd.concat([cal_continent, population_continent, cal_requirements_continent, cropland_per_continent, sufficiency_continent, cal_perc_continent, cropland_yield_continent], axis=1) 
    continent.columns = ['Calories 2050', 'Population 2050', 'Calory requirements 2050', 'Cropland (%) 2050', 'Sufficiency (%) 2050', 'Percentage of total cal 2050', 'Yield 2050']
    
    # Delta continent 2050
    delta_cal_continent = 100*scenario.groupby('continent')['ΔCalories'].sum() / continent_2000['Calories 2000']
    delta_pop_continent = 100*(continent['Population 2050'] - continent_2000['Population 2000']) / continent_2000['Population 2000']
    delta_yield_continent = 100*(continent['Yield 2050'] - continent_2000['Yield 2000']) / continent_2000['Yield 2000']
    delta_cal_req_continent = 100*(continent['Calory requirements 2050'] - continent_2000['Calory requirements 2000']) / continent_2000['Calory requirements 2000']
    delta_continent = pd.concat([delta_cal_continent, delta_pop_continent, delta_cal_req_continent, delta_yield_continent], axis=1)
    delta_continent.columns = ['ΔCalories (%)', 'ΔPopulation (%)', 'ΔCalory requirements (%)', 'ΔYield (%)']
    continent = continent_2000.join(continent, on='continent').join(delta_continent, on='continent')
     
    country.to_csv(graph_path + 'graph_country_' + name + '.csv')
    continent.to_csv(graph_path + 'graph_continent_' + name + '.csv')
    
    demand_2050 = country['Calory requirements 2050'].sum()
    production_2050 = country['Calories 2050'].sum()
    print('{}:\nWorld demand 2050: {:,}\nWorld production 2050: {:,}\n'.format(name, demand_2050, production_2050))

SSP1:
World demand 2050: 6.462865142385013e+18
World production 2050: 1.2839836723806478e+19

SSP2:
World demand 2050: 7.089486962235677e+18
World production 2050: 1.3919600736108294e+19

SSP3:
World demand 2050: 7.64763662936687e+18
World production 2050: 1.3961521626148364e+19

SSP4:
World demand 2050: 7.091832712143241e+18
World production 2050: 1.4116790470417613e+19

SSP5:
World demand 2050: 6.54418318208792e+18
World production 2050: 1.4134456685394004e+19