In [15]:
import pandas as pd
import numpy as np
import math

import matplotlib.pyplot as plt
%matplotlib inline
import os

In [16]:
countries = set()

In [17]:
path = 'data/2050/SSP2'

In [18]:
files = os.listdir(path)
files[:5]

['SSP2_Georgia.csv',
 'SSP2_United Arab Emirates.csv',
 'SSP2_Sri Lanka.csv',
 'SSP2_Honduras.csv',
 'SSP2_Albania.csv']

In [19]:
for file in files:
    countries.add(file[5:-4])
len(countries)

181

In [20]:
countries = list(countries)
countries[:10]

['Hungary',
 'Kazakhstan',
 'Argentina',
 'Bangladesh',
 'Cameroon',
 'Zambia',
 'Kenya',
 'Algeria',
 'Portugal',
 'The Bahamas']

In [49]:
gdp = pd.read_csv(graph_path + 'gdp_2017.csv')

c = list(gdp['Country'])

r = [country for country in countries if country in c]
bibi = gdp[gdp['Country'].isin(r)]
bibi[bibi['gdp2017'] == 0]

     Unnamed: 0                           Country  gdp2017
17           17                       The Bahamas      0.0
23           23                            Brunei      0.0
31           31                       Ivory Coast      0.0
33           33  Democratic Republic of the Congo      0.0
34           34             Republic of the Congo      0.0
37           37                              Cuba      0.0
48           48                           Eritrea      0.0
54           54                  Falkland Islands      0.0
61           61                            Gambia      0.0
62           62                     Guinea Bissau      0.0
65           65                         Greenland      0.0
75           75                              Iran      0.0
85           85                        Kyrgyzstan      0.0
87           87                       South Korea      0.0
90           90                              Laos      0.0
97           97                        Luxembourg      0.0
103         103                         Macedonia      0.0
113         113                     New Caledonia      0.0
128         128                       Puerto Rico      0.0
129         129                       North Korea      0.0
132         132                             Qatar      0.0
136         136                    Western Sahara      0.0
139         139                       South Sudan      0.0
146         146                Republic of Serbia      0.0
148         148                          Slovakia      0.0
151         151                         Swaziland      0.0
152         152                             Syria      0.0
158         158                        East Timor      0.0
162         162                            Taiwan      0.0
163         163       United Republic of Tanzania      0.0
169         169                         Venezuela      0.0
172         172                         West Bank      0.0
173         173                             Yemen      0.0

In [41]:
gdp.to_csv(graph_path + 'gdp_2017.csv')

In [7]:
"""graph_path = 'data/graph/'

country_ssp1 = pd.read_csv(graph_path + 'graph_country_data_ssp1.csv', na_values=[0, np.inf])
country_ssp2 = pd.read_csv(graph_path + 'graph_country_data_ssp2.csv', na_values=[0, np.inf])
country_ssp3 = pd.read_csv(graph_path + 'graph_country_data_ssp3.csv', na_values=[0, np.inf])
country_ssp4 = pd.read_csv(graph_path + 'graph_country_data_ssp4.csv', na_values=[0, np.inf])
country_ssp5 = pd.read_csv(graph_path + 'graph_country_data_ssp5.csv', na_values=[0, np.inf])

continent_ssp1 = pd.read_csv(graph_path + 'graph_continent_data_ssp1.csv', na_values=[0, np.inf])
continent_ssp2 = pd.read_csv(graph_path + 'graph_continent_data_ssp2.csv', na_values=[0, np.inf])
continent_ssp3 = pd.read_csv(graph_path + 'graph_continent_data_ssp3.csv', na_values=[0, np.inf])
continent_ssp4 = pd.read_csv(graph_path + 'graph_continent_data_ssp4.csv', na_values=[0, np.inf])
continent_ssp5 = pd.read_csv(graph_path + 'graph_continent_data_ssp5.csv', na_values=[0, np.inf])"""

In [8]:
"""columns = ['Country', 'Calories2000', 'Population2000', 'Caloryrequirements2000',
       'Cropland2000', 'Sufficiency2000', 'Percentageoftotalcal2000',
       'Yield2000', 'Calories2050', 'Population2050', 'Caloryrequirements2050',
       'Cropland2050', 'Sufficiency2050', 'Percentageoftotalcal2050',
       'Yield2050', 'diffCalories', 'diffPopulation', 'diffCaloryrequirements',
       'diffYield']"""

In [9]:
"""country_ssp1.columns = columns
country_ssp2.columns = columns
country_ssp3.columns = columns
country_ssp4.columns = columns
country_ssp5.columns = columns

continent_ssp1.columns = columns
continent_ssp2.columns = columns
continent_ssp3.columns = columns
continent_ssp4.columns = columns
continent_ssp5.columns = columns

world_ssp1 = country_ssp1.sum()
world_ssp2 = country_ssp1.sum()
world_ssp3 = country_ssp1.sum()
world_ssp4 = country_ssp1.sum()
world_ssp5 = country_ssp1.sum()

world_ssp1['Country'] = 'World'
world_ssp2['Country'] = 'World'
world_ssp3['Country'] = 'World'
world_ssp4['Country'] = 'World'
world_ssp5['Country'] = 'World'

world_ssp1 = pd.DataFrame(world_ssp1).transpose()
world_ssp2 = pd.DataFrame(world_ssp2).transpose()
world_ssp3 = pd.DataFrame(world_ssp3).transpose()
world_ssp4 = pd.DataFrame(world_ssp4).transpose()
world_ssp5 = pd.DataFrame(world_ssp5).transpose()"""

In [10]:
"""ssp1 = pd.concat([country_ssp1, continent_ssp1, world_ssp1]).reset_index(drop=True)
ssp2 = pd.concat([country_ssp2, continent_ssp2, world_ssp2]).reset_index(drop=True)
ssp3 = pd.concat([country_ssp3, continent_ssp3, world_ssp3]).reset_index(drop=True)
ssp4 = pd.concat([country_ssp4, continent_ssp4, world_ssp4]).reset_index(drop=True)
ssp5 = pd.concat([country_ssp5, continent_ssp5, world_ssp5]).reset_index(drop=True)"""

In [11]:
"""ssp1.to_csv(graph_path + 'SSP1.csv')
ssp2.to_csv(graph_path + 'SSP2.csv')
ssp3.to_csv(graph_path + 'SSP3.csv')
ssp4.to_csv(graph_path + 'SSP4.csv')
ssp5.to_csv(graph_path + 'SSP5.csv')"""